"""init db

Revision ID: ef6118a0242f
Revises: 
Create Date: 2026-04-25 15:11:24.148550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6118a0242f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aps_calendar',
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('day_of_week_cd', sa.String(length=20), nullable=True),
    sa.Column('work_gb_cd', sa.String(length=20), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('work_hours', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.CheckConstraint('work_hours >= 0', name='ck_calendar_work_hours_non_negative'),
    sa.PrimaryKeyConstraint('work_date'),
    schema='aps_input'
    )
    op.create_table('aps_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_no', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.CheckConstraint("customer_type IN ('internal','small','normal','important','vip')", name='ck_customer_type'),
    sa.CheckConstraint('impact_score BETWEEN 1 AND 5', name='ck_customer_impact_score'),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_input'
    )
    op.create_index(op.f('ix_aps_input_aps_customer_customer_no'), 'aps_customer', ['customer_no'], unique=True, schema='aps_input')
    op.create_table('aps_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_no', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=True),
    sa.Column('spec', sa.String(length=200), nullable=True),
    sa.CheckConstraint("asset_type IN ('Product','SemiProduct','RawMaterial')", name='ck_item_asset_type'),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_input'
    )
    op.create_index(op.f('ix_aps_input_aps_item_item_no'), 'aps_item', ['item_no'], unique=True, schema='aps_input')
    op.create_table('aps_routing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gsystem_id', sa.Integer(), nullable=True),
    sa.Column('routing_no', sa.String(length=50), nullable=True),
    sa.Column('routing_name', sa.String(length=200), nullable=True),
    sa.Column('routing_type_cd', sa.String(length=20), nullable=True),
    sa.Column('std_capa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gsystem_id'),
    schema='aps_input'
    )
    op.create_table('aps_schedule_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('horizon_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('solver_status', sa.String(length=64), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_input'
    )
    op.create_index(op.f('ix_aps_input_aps_schedule_run_status'), 'aps_schedule_run', ['status'], unique=False, schema='aps_input')
    op.create_table('aps_stock',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('corp_id', sa.String(length=50), nullable=True),
    sa.Column('parea_id', sa.String(length=50), nullable=True),
    sa.Column('biz_id', sa.String(length=50), nullable=True),
    sa.Column('stk_ym', sa.String(length=10), nullable=True),
    sa.Column('stk_type', sa.String(length=20), nullable=True),
    sa.Column('wh_cd', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('item_id', sa.String(length=50), nullable=True),
    sa.Column('unit_cd', sa.String(length=20), nullable=True),
    sa.Column('lotno', sa.String(length=100), nullable=True),
    sa.Column('prev_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('prev_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('prev_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('in_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('buy_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('buy_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('make_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('make_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('etc_in_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('etc_in_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mv_in_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mv_in_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('out_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('invoice_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('invoice_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mat_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mat_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mv_out_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('mv_out_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('etc_out_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('etc_out_amt', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('able_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reg_user_id', sa.String(length=50), nullable=True),
    sa.Column('reg_dt', sa.DateTime(), nullable=True),
    sa.Column('reg_ip', sa.String(length=50), nullable=True),
    sa.Column('mod_user_id', sa.String(length=50), nullable=True),
    sa.Column('mod_dt', sa.DateTime(), nullable=True),
    sa.Column('mod_ip', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_input'
    )
    op.create_index(op.f('ix_aps_input_aps_stock_able_qty'), 'aps_stock', ['able_qty'], unique=False, schema='aps_input')
    op.create_index(op.f('ix_aps_input_aps_stock_item_id'), 'aps_stock', ['item_id'], unique=False, schema='aps_input')
    op.create_index(op.f('ix_aps_input_aps_stock_stk_ym'), 'aps_stock', ['stk_ym'], unique=False, schema='aps_input')
    op.create_index(op.f('ix_aps_input_aps_stock_wh_cd'), 'aps_stock', ['wh_cd'], unique=False, schema='aps_input')
    op.create_table('aps_workcenter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gsystem_id', sa.Integer(), nullable=True),
    sa.Column('workcenter_no', sa.String(length=50), nullable=False),
    sa.Column('workcenter_name', sa.String(length=200), nullable=True),
    sa.Column('workshop_cd', sa.String(length=50), nullable=True),
    sa.Column('std_capa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.CheckConstraint('std_capa IS NULL OR std_capa >= 0', name='ck_workcenter_std_capa_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gsystem_id'),
    schema='aps_input'
    )
    op.create_index(op.f('ix_aps_input_aps_workcenter_workcenter_no'), 'aps_workcenter', ['workcenter_no'], unique=True, schema='aps_input')
    op.create_table('plan_scenario',
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('horizon_start', sa.Date(), nullable=False),
    sa.Column('horizon_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('scenario_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('what_if_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('scenario_id'),
    schema='aps_result'
    )
    op.create_index(op.f('ix_aps_result_plan_scenario_created_at'), 'plan_scenario', ['created_at'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_scenario_name'), 'plan_scenario', ['name'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_scenario_status'), 'plan_scenario', ['status'], unique=False, schema='aps_result')
    op.create_table('aps_bom',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_item_id'], ['aps_input.aps_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_input'
    )
    op.create_table('aps_demand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_no', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('plan_qty', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('plan_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('status_cd', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['aps_input.aps_customer.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['aps_input.aps_item.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['aps_input.aps_routing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_input'
    )
    op.create_index(op.f('ix_aps_input_aps_demand_plan_no'), 'aps_demand', ['plan_no'], unique=True, schema='aps_input')
    op.create_table('aps_item_process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('gsystem_proc_id', sa.Integer(), nullable=True),
    sa.Column('proc_sno', sa.Integer(), nullable=False),
    sa.Column('making_gb', sa.String(length=20), nullable=True),
    sa.Column('inspection_yn', sa.Boolean(), nullable=True),
    sa.Column('work_ins_yn', sa.Boolean(), nullable=True),
    sa.Column('stock_yn', sa.Boolean(), nullable=True),
    sa.Column('rev_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['aps_input.aps_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'proc_sno'),
    schema='aps_input'
    )
    op.create_index(op.f('ix_aps_input_aps_item_process_gsystem_proc_id'), 'aps_item_process', ['gsystem_proc_id'], unique=False, schema='aps_input')
    op.create_index(op.f('ix_aps_input_aps_item_process_item_id'), 'aps_item_process', ['item_id'], unique=False, schema='aps_input')
    op.create_table('aps_operation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('process_seq', sa.Integer(), nullable=False),
    sa.Column('gsystem_process_id', sa.Integer(), nullable=True),
    sa.Column('proc_no', sa.String(length=50), nullable=True),
    sa.Column('proc_name', sa.String(length=200), nullable=True),
    sa.Column('workcenter_id', sa.Integer(), nullable=True),
    sa.Column('work_time_hours', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('setup_time_hours', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.CheckConstraint('setup_time_hours IS NULL OR setup_time_hours >= 0', name='ck_operation_setup_time_non_negative'),
    sa.CheckConstraint('work_time_hours IS NULL OR work_time_hours >= 0', name='ck_operation_work_time_non_negative'),
    sa.ForeignKeyConstraint(['routing_id'], ['aps_input.aps_routing.id'], ),
    sa.ForeignKeyConstraint(['workcenter_id'], ['aps_input.aps_workcenter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_id', 'process_seq'),
    schema='aps_input'
    )
    op.create_table('aps_routing_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['aps_input.aps_item.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['aps_input.aps_routing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_id', 'item_id'),
    schema='aps_input'
    )
    op.create_table('plan_evaluation_summary',
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('due_date_compliance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('due_date_status', sa.String(length=20), nullable=False),
    sa.Column('material_shortage_cnt', sa.Integer(), nullable=False),
    sa.Column('material_status', sa.String(length=20), nullable=False),
    sa.Column('max_utilization_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('utilization_status', sa.String(length=20), nullable=False),
    sa.Column('risk_count', sa.Integer(), nullable=False),
    sa.Column('risk_status', sa.String(length=20), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_scenario.scenario_id'], ),
    sa.PrimaryKeyConstraint('scenario_id'),
    schema='aps_result'
    )
    op.create_index(op.f('ix_aps_result_plan_evaluation_summary_evaluated_at'), 'plan_evaluation_summary', ['evaluated_at'], unique=False, schema='aps_result')
    op.create_table('plan_utilization',
    sa.Column('utilization_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('workcenter_id', sa.String(length=50), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('utilization_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('available_capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('used_capacity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_scenario.scenario_id'], ),
    sa.PrimaryKeyConstraint('utilization_id'),
    sa.UniqueConstraint('scenario_id', 'workcenter_id', 'plan_date', name='idx_plan_utilization_scenario_workcenter_date'),
    schema='aps_result'
    )
    op.create_index('idx_plan_utilization_date', 'plan_utilization', ['plan_date'], unique=False, schema='aps_result')
    op.create_index('idx_plan_utilization_scenario', 'plan_utilization', ['scenario_id'], unique=False, schema='aps_result')
    op.create_index('idx_plan_utilization_workcenter', 'plan_utilization', ['workcenter_id'], unique=False, schema='aps_result')
    op.create_table('aps_bom_component',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('component_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bom_seq', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['aps_input.aps_bom.id'], ),
    sa.ForeignKeyConstraint(['component_item_id'], ['aps_input.aps_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_input'
    )
    op.create_table('aps_scheduled_operation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_run_id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('schedule_lot_key', sa.String(length=200), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('workcenter_id', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['aps_input.aps_demand.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['aps_input.aps_operation.id'], ),
    sa.ForeignKeyConstraint(['routing_id'], ['aps_input.aps_routing.id'], ),
    sa.ForeignKeyConstraint(['schedule_run_id'], ['aps_input.aps_schedule_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workcenter_id'], ['aps_input.aps_workcenter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_input'
    )
    op.create_index(op.f('ix_aps_input_aps_scheduled_operation_schedule_lot_key'), 'aps_scheduled_operation', ['schedule_lot_key'], unique=False, schema='aps_input')
    op.create_index(op.f('ix_aps_input_aps_scheduled_operation_schedule_run_id'), 'aps_scheduled_operation', ['schedule_run_id'], unique=False, schema='aps_input')
    op.create_table('plan_evaluation_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_evaluation_summary.scenario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_result'
    )
    op.create_index(op.f('ix_aps_result_plan_evaluation_action_action_type'), 'plan_evaluation_action', ['action_type'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_evaluation_action_enabled'), 'plan_evaluation_action', ['enabled'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_evaluation_action_plan_id'), 'plan_evaluation_action', ['plan_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_evaluation_action_scenario_id'), 'plan_evaluation_action', ['scenario_id'], unique=False, schema='aps_result')
    op.create_table('plan_evaluation_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=True),
    sa.Column('metric_type', sa.String(length=20), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_evaluation_summary.scenario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='aps_result'
    )
    op.create_index(op.f('ix_aps_result_plan_evaluation_detail_metric_type'), 'plan_evaluation_detail', ['metric_type'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_evaluation_detail_plan_id'), 'plan_evaluation_detail', ['plan_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_evaluation_detail_ref_type'), 'plan_evaluation_detail', ['ref_type'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_evaluation_detail_scenario_id'), 'plan_evaluation_detail', ['scenario_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_evaluation_detail_severity'), 'plan_evaluation_detail', ['severity'], unique=False, schema='aps_result')
    op.create_table('plan_order',
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=True),
    sa.Column('demand_line_id', sa.String(length=50), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=False),
    sa.Column('planned_finish_date', sa.Date(), nullable=False),
    sa.Column('planned_ship_date', sa.Date(), nullable=False),
    sa.Column('plan_status', sa.String(length=20), nullable=False),
    sa.Column('late_days', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('priority_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['aps_input.aps_demand.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_scenario.scenario_id'], ),
    sa.PrimaryKeyConstraint('plan_id'),
    schema='aps_result'
    )
    op.create_index(op.f('ix_aps_result_plan_order_demand_id'), 'plan_order', ['demand_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_order_demand_line_id'), 'plan_order', ['demand_line_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_order_plan_status'), 'plan_order', ['plan_status'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_order_planned_finish_date'), 'plan_order', ['planned_finish_date'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_order_planned_start_date'), 'plan_order', ['planned_start_date'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_order_run_id'), 'plan_order', ['run_id'], unique=False, schema='aps_result')
    op.create_table('workcenter_load',
    sa.Column('load_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('workcenter_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('proc_name', sa.String(length=200), nullable=True),
    sa.Column('used_minutes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('capacity_minutes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('load_percent', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('overloaded', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['aps_input.aps_operation.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_scenario.scenario_id'], ),
    sa.ForeignKeyConstraint(['workcenter_id'], ['aps_input.aps_workcenter.id'], ),
    sa.PrimaryKeyConstraint('load_id'),
    schema='aps_result'
    )
    op.create_index('idx_workcenter_load_operation', 'workcenter_load', ['operation_id'], unique=False, schema='aps_result')
    op.create_index('idx_workcenter_load_scenario_date', 'workcenter_load', ['scenario_id', 'work_date'], unique=False, schema='aps_result')
    op.create_index('idx_workcenter_load_workcenter', 'workcenter_load', ['workcenter_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_workcenter_load_operation_id'), 'workcenter_load', ['operation_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_workcenter_load_run_id'), 'workcenter_load', ['run_id'], unique=False, schema='aps_result')
    op.create_table('plan_impacted_order',
    sa.Column('impacted_id', sa.String(length=50), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('demand_id', sa.Integer(), nullable=True),
    sa.Column('reason_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['aps_input.aps_demand.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['aps_result.plan_order.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_scenario.scenario_id'], ),
    sa.PrimaryKeyConstraint('impacted_id'),
    schema='aps_result'
    )
    op.create_index('idx_plan_impacted_order_plan', 'plan_impacted_order', ['plan_id'], unique=False, schema='aps_result')
    op.create_index('idx_plan_impacted_order_reason', 'plan_impacted_order', ['reason_type'], unique=False, schema='aps_result')
    op.create_index('idx_plan_impacted_order_scenario', 'plan_impacted_order', ['scenario_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_impacted_order_demand_id'), 'plan_impacted_order', ['demand_id'], unique=False, schema='aps_result')
    op.create_table('plan_operation',
    sa.Column('plan_op_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('op_code', sa.String(length=50), nullable=False),
    sa.Column('workcenter_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('routing_id', sa.Integer(), nullable=False),
    sa.Column('planned_start_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end_dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('load_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['aps_input.aps_operation.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['aps_result.plan_order.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routing_id'], ['aps_input.aps_routing.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_scenario.scenario_id'], ),
    sa.ForeignKeyConstraint(['workcenter_id'], ['aps_input.aps_workcenter.id'], ),
    sa.PrimaryKeyConstraint('plan_op_id'),
    schema='aps_result'
    )
    op.create_index(op.f('ix_aps_result_plan_operation_operation_id'), 'plan_operation', ['operation_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_operation_planned_end_dt'), 'plan_operation', ['planned_end_dt'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_operation_planned_start_dt'), 'plan_operation', ['planned_start_dt'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_operation_workcenter_id'), 'plan_operation', ['workcenter_id'], unique=False, schema='aps_result')
    op.create_table('plan_shortage',
    sa.Column('shortage_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('op_code', sa.String(length=50), nullable=False),
    sa.Column('need_date', sa.Date(), nullable=False),
    sa.Column('required_qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('available_qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('shortage_qty', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('cause', sa.String(length=20), nullable=False),
    sa.Column('scenario_id', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['aps_input.aps_item.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['aps_result.plan_order.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['aps_result.plan_scenario.scenario_id'], ),
    sa.PrimaryKeyConstraint('shortage_id'),
    schema='aps_result'
    )
    op.create_index(op.f('ix_aps_result_plan_shortage_cause'), 'plan_shortage', ['cause'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_shortage_item_id'), 'plan_shortage', ['item_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_shortage_need_date'), 'plan_shortage', ['need_date'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_shortage_op_code'), 'plan_shortage', ['op_code'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_shortage_plan_id'), 'plan_shortage', ['plan_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_shortage_scenario_id'), 'plan_shortage', ['scenario_id'], unique=False, schema='aps_result')
    op.create_index(op.f('ix_aps_result_plan_shortage_shortage_qty'), 'plan_shortage', ['shortage_qty'], unique=False, schema='aps_result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aps_result_plan_shortage_shortage_qty'), table_name='plan_shortage', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_shortage_scenario_id'), table_name='plan_shortage', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_shortage_plan_id'), table_name='plan_shortage', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_shortage_op_code'), table_name='plan_shortage', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_shortage_need_date'), table_name='plan_shortage', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_shortage_item_id'), table_name='plan_shortage', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_shortage_cause'), table_name='plan_shortage', schema='aps_result')
    op.drop_table('plan_shortage', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_operation_workcenter_id'), table_name='plan_operation', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_operation_planned_start_dt'), table_name='plan_operation', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_operation_planned_end_dt'), table_name='plan_operation', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_operation_operation_id'), table_name='plan_operation', schema='aps_result')
    op.drop_table('plan_operation', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_impacted_order_demand_id'), table_name='plan_impacted_order', schema='aps_result')
    op.drop_index('idx_plan_impacted_order_scenario', table_name='plan_impacted_order', schema='aps_result')
    op.drop_index('idx_plan_impacted_order_reason', table_name='plan_impacted_order', schema='aps_result')
    op.drop_index('idx_plan_impacted_order_plan', table_name='plan_impacted_order', schema='aps_result')
    op.drop_table('plan_impacted_order', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_workcenter_load_run_id'), table_name='workcenter_load', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_workcenter_load_operation_id'), table_name='workcenter_load', schema='aps_result')
    op.drop_index('idx_workcenter_load_workcenter', table_name='workcenter_load', schema='aps_result')
    op.drop_index('idx_workcenter_load_scenario_date', table_name='workcenter_load', schema='aps_result')
    op.drop_index('idx_workcenter_load_operation', table_name='workcenter_load', schema='aps_result')
    op.drop_table('workcenter_load', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_order_run_id'), table_name='plan_order', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_order_planned_start_date'), table_name='plan_order', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_order_planned_finish_date'), table_name='plan_order', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_order_plan_status'), table_name='plan_order', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_order_demand_line_id'), table_name='plan_order', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_order_demand_id'), table_name='plan_order', schema='aps_result')
    op.drop_table('plan_order', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_detail_severity'), table_name='plan_evaluation_detail', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_detail_scenario_id'), table_name='plan_evaluation_detail', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_detail_ref_type'), table_name='plan_evaluation_detail', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_detail_plan_id'), table_name='plan_evaluation_detail', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_detail_metric_type'), table_name='plan_evaluation_detail', schema='aps_result')
    op.drop_table('plan_evaluation_detail', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_action_scenario_id'), table_name='plan_evaluation_action', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_action_plan_id'), table_name='plan_evaluation_action', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_action_enabled'), table_name='plan_evaluation_action', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_action_action_type'), table_name='plan_evaluation_action', schema='aps_result')
    op.drop_table('plan_evaluation_action', schema='aps_result')
    op.drop_index(op.f('ix_aps_input_aps_scheduled_operation_schedule_run_id'), table_name='aps_scheduled_operation', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_scheduled_operation_schedule_lot_key'), table_name='aps_scheduled_operation', schema='aps_input')
    op.drop_table('aps_scheduled_operation', schema='aps_input')
    op.drop_table('aps_bom_component', schema='aps_input')
    op.drop_index('idx_plan_utilization_workcenter', table_name='plan_utilization', schema='aps_result')
    op.drop_index('idx_plan_utilization_scenario', table_name='plan_utilization', schema='aps_result')
    op.drop_index('idx_plan_utilization_date', table_name='plan_utilization', schema='aps_result')
    op.drop_table('plan_utilization', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_evaluation_summary_evaluated_at'), table_name='plan_evaluation_summary', schema='aps_result')
    op.drop_table('plan_evaluation_summary', schema='aps_result')
    op.drop_table('aps_routing_item', schema='aps_input')
    op.drop_table('aps_operation', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_item_process_item_id'), table_name='aps_item_process', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_item_process_gsystem_proc_id'), table_name='aps_item_process', schema='aps_input')
    op.drop_table('aps_item_process', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_demand_plan_no'), table_name='aps_demand', schema='aps_input')
    op.drop_table('aps_demand', schema='aps_input')
    op.drop_table('aps_bom', schema='aps_input')
    op.drop_index(op.f('ix_aps_result_plan_scenario_status'), table_name='plan_scenario', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_scenario_name'), table_name='plan_scenario', schema='aps_result')
    op.drop_index(op.f('ix_aps_result_plan_scenario_created_at'), table_name='plan_scenario', schema='aps_result')
    op.drop_table('plan_scenario', schema='aps_result')
    op.drop_index(op.f('ix_aps_input_aps_workcenter_workcenter_no'), table_name='aps_workcenter', schema='aps_input')
    op.drop_table('aps_workcenter', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_stock_wh_cd'), table_name='aps_stock', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_stock_stk_ym'), table_name='aps_stock', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_stock_item_id'), table_name='aps_stock', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_stock_able_qty'), table_name='aps_stock', schema='aps_input')
    op.drop_table('aps_stock', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_schedule_run_status'), table_name='aps_schedule_run', schema='aps_input')
    op.drop_table('aps_schedule_run', schema='aps_input')
    op.drop_table('aps_routing', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_item_item_no'), table_name='aps_item', schema='aps_input')
    op.drop_table('aps_item', schema='aps_input')
    op.drop_index(op.f('ix_aps_input_aps_customer_customer_no'), table_name='aps_customer', schema='aps_input')
    op.drop_table('aps_customer', schema='aps_input')
    op.drop_table('aps_calendar', schema='aps_input')
    # ### end Alembic commands ###
